version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https://music-test-backend-1.onrender.com/
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
